"""Centralized configuration for the YouTube Shorts automation tool."""

from pathlib import Path

VERTICAL_WIDTH = 1080
VERTICAL_HEIGHT = 1920
TARGET_FPS = 30

DEFAULT_MIN_CLIP_DURATION = 30
DEFAULT_MAX_CLIP_DURATION = 90
DEFAULT_MAX_CLIPS = 5
HARD_MAX_CLIPS = 7

TARGET_LUFS = -14.0
LUFS_TRUE_PEAK = -1.5
LUFS_LRA = 11.0

FADE_IN_DURATION = 0.3
FADE_OUT_DURATION = 0.3

SUBTITLE_FONT = "Montserrat ExtraBold"
SUBTITLE_FONT_SIZE = 64
SUBTITLE_PRIMARY_COLOR = "&H00FFFFFF"
SUBTITLE_OUTLINE_COLOR = "&H00000000"
SUBTITLE_HIGHLIGHT_COLOR = "&H0000A5FF"  # punchy amber/orange highlight for the active word (ASS BGR)
SUBTITLE_OUTLINE_WIDTH = 4
SUBTITLE_SHADOW_DEPTH = 2
SUBTITLE_BOTTOM_MARGIN = 280

WHISPER_MODEL = "base"
WHISPER_DEFAULT_LANGUAGE = "en"

OUTPUT_DIR = Path("output")
LOG_FILE = "debug.log"

MIN_VALID_CLIP_BYTES = 500 * 1024

VIDEO_FORMAT = "bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best"
